#!/usr/bin/python3
'''
Program to vote 1024 times
to the Hodor project from
Holberton School
'''


# Import module
import requests
try:
    from PIL import Image
except ImportError:
    import Image
import pytesseract

# Level 3
times = 1024
URL = 'http://158.69.76.135/level3.php'
windows_user = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36")
header = {"User-Agent": windows_user, "Referer": URL}
url_captcha = 'http://158.69.76.135/captcha.php'

for i in range(times):
    try:
        with requests.Session() as session:
            # Get the response object by get method
            response = session.get(URL, headers=header)
            # get image response object
            image = session.get(url_captcha, headers=header)

            # write captcha file
            image_file = open('captcha.png', 'wb')
            image_file.write(i.content)
            image_file.close()

            # Solve captcha with pytesseract
            captcha = pytesseract.image_to_string(Image.open('captcha.png'))
            captcha = captcha.replace(" ", "").strip()

            # Obtaining the key from cookies
            key = session.cookies['HoldTheDoor']
            # Composing the data that will be send
            my_id = {
                    'id': 2282, 'key': key,
                    'captcha': captcha, 'holdthedoor': 'submit'
                    }
            # Send the data
            response_post = session.post(URL, headers=header, data=my_id)
            print('Status: {}'.format(response_post.status_code))
    except Exception as error:
        print(error)

print("Cheat online voting process finished :)")
